# -------------------------------------------
# Commands to run this compose file:
# - docker-compose -p inft1206-environment -f docker-compose.yml up -d
# - docker-compose -p inft1206-environment -f docker-compose.yml up -d --build (forces rebuild)
# -------------------------------------------

services:

  web-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    container_name: inft1206-web-app
    volumes:
      - .:/var/www/html
    environment:
      - XDEBUG_MODE=debug
      - XDEBUG_CONFIG=client_host=host.docker.internal
      - PHP_IDE_CONFIG=serverName=DockerServer
    depends_on:
      - postgres-php

  postgres-php:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    container_name: inft1206-postgres

  pgpadmin:
    image: dpage/pgadmin4:9.2
    ports:
      - "8888:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.ca
      - PGADMIN_DEFAULT_PASSWORD=password
    container_name: inft1206-pgadmingui